### ISSUE TITLE
Lights not working properly

### ISSUE THREAD

**Issue by anrl** [anrl/gini5#24]
They are not turning green on the UMLs.
They remain yellow even after opening the window.

**Comment by trungams** [comment]
Solution is to open the docker shell with `screen`. 2 concerns:
- With simple flags like `screen -r <sessionid> <command>` the shell displays no command prompt at all, while it should show something like `$ `. I will see what might be causing it.
- When exiting the shell using `exit` command or simply close the terminal window. How should the virtual machine's status change? Right now it will be dead on `exit` command, and will turn to detached if the window is simply closed
