### ISSUE TITLE
"TypeError" when running a network topology

### ISSUE THREAD

**Issue by trungams** [anrl/gini5#25]
This seemingly simple mixed network with a switch device and a router cannot be started due to a TypeError:
![image](https://user-images.githubusercontent.com/25715630/50556732-efe13c00-0caa-11e9-9cd6-9e6e7285eadb.png)

Error message:
![image](https://user-images.githubusercontent.com/25715630/50556730-e6f06a80-0caa-11e9-9b49-f9afe4a4e1f0.png)

Seems like an error on front-end from looking at the stack trace. gserver does not even have the chance to output anything so I'm quite convinced.

In case it's a back-end issue, keep in mind that virtual switches are created before virtual routers.

**Comment by anrl** [comment]
This is the most important next task

**Comment by trungams** [comment]
Temporary solution: add a new connection rule for subnet. One adjacent node of a subnet must be a router
