### ISSUE TITLE
This config does not work

### ISSUE THREAD

**Issue by anrl** [anrl/gini5#6]
<img width="443" alt="screen shot 2018-12-06 at 1 12 46 am" src="https://user-images.githubusercontent.com/1151354/49565119-1c947480-f8f4-11e8-87e4-65bd440074d7.png">

**Comment by anrl** [comment]
The ping goes to the destination. The replies do not come back!

**Comment by anrl** [comment]
I figured out the problem. It is still the same problem as the "tap" interface naming.
Well, the tap interfaces are named based on the switches. And the switches are also named in a crude way. So we need to revise that procedure.

In the above topology, only three switches are created. We need to create 4 switches. One for each subnet. 

The one for subnet_2 is missing.

**Comment by trungams** [comment]
Resolved in cca0a2e1a0c895a5c2c6456fd47f772a31625308
